name: install Buck2
author: David Tolnay
description: Prebuilt binaries of https://buck2.build
branding:
  icon: activity
  color: purple

runs:
  using: composite
  steps:
    - id: configure
      run: |
        echo platform=${{runner.os == 'macOS' && 'x86_64-apple-darwin' || runner.os == 'Windows' && 'x86_64-pc-windows-msvc.exe' || 'x86_64-unknown-linux-gnu'}} >> $GITHUB_OUTPUT
        echo filename=${{runner.os == 'Windows' && 'buck2.exe' || 'buck2'}} >> $GITHUB_OUTPUT
      shell: bash

    - run: mkdir -p "${{runner.temp}}/install-buck2/bin"
      shell: bash

    - run: curl https://github.com/facebook/buck2/releases/download/latest/buck2-${{steps.configure.outputs.platform}}.zst --output "${{runner.temp}}/install-buck2/${{steps.configure.outputs.filename}}.zst" --location --silent --show-error --fail --retry 5
      shell: bash

    - run: zstd -d "${{runner.temp}}/install-buck2/${{steps.configure.outputs.filename}}.zst" -o "${{runner.temp}}/install-buck2/bin/${{steps.configure.outputs.filename}}"
      shell: bash

    - run: chmod +x "${{runner.temp}}/install-buck2/bin/${{steps.configure.outputs.filename}}"
      shell: bash

    - run: echo "${{runner.temp}}/install-buck2/bin" >> $GITHUB_PATH
      shell: bash

    - run: sudo apt-get install lld
      if: runner.os == 'Linux'
      shell: bash

    - run: buck2 --version
      shell: bash
