name: install Buck2
author: David Tolnay
description: Prebuilt binaries of https://buck2.build
branding:
  icon: activity
  color: purple

inputs:
  prelude-submodule:
    description: Path to checkout https://github.com/facebook/buck2-prelude as a submodule
    required: false

outputs:
  prelude-hash:
    description:
    value: ${{steps.prelude-hash.outputs.prelude-hash}}

runs:
  using: composite
  steps:
    - id: configure
      run: |
        echo platform=${{runner.os == 'macOS' && 'x86_64-apple-darwin' || runner.os == 'Windows' && 'x86_64-pc-windows-msvc' || 'x86_64-unknown-linux-gnu'}} >> $GITHUB_OUTPUT
        echo extension=${{runner.os == 'Windows' && '.exe' || ''}} >> $GITHUB_OUTPUT
      shell: bash

    - run: mkdir -p "${{runner.temp}}/install-buck2/bin"
      shell: bash

    - run: curl https://github.com/facebook/buck2/releases/download/latest/buck2-${{steps.configure.outputs.platform}}${{steps.configure.outputs.extension}}.zst --output "${{runner.temp}}/install-buck2/buck2${{steps.configure.outputs.extension}}.zst" --location --silent --show-error --fail --retry 5
      shell: bash

    - id: prelude-hash
      run: curl https://github.com/facebook/buck2/releases/download/latest/prelude_hash --location --silent --show-error --fail --retry 5 | sed 's/^/prelude-hash=/' >> $GITHUB_OUTPUT
      shell: bash

    - run: zstd -d "${{runner.temp}}/install-buck2/buck2${{steps.configure.outputs.extension}}.zst" -o "${{runner.temp}}/install-buck2/bin/buck2${{steps.configure.outputs.extension}}"
      shell: bash

    - run: chmod +x "${{runner.temp}}/install-buck2/bin/buck2${{steps.configure.outputs.extension}}"
      shell: bash

    - run: ln -s "${{runner.temp}}/install-buck2/bin/buck2${{steps.configure.outputs.extension}}" "${{runner.temp}}/install-buck2/bin/buck${{steps.configure.outputs.extension}}"
      shell: bash

    - run: echo "${{runner.temp}}/install-buck2/bin" >> $GITHUB_PATH
      shell: bash

    - run: mkdir -p -- "${{inputs.prelude-submodule}}"
      if: inputs.prelude-submodule != ''
      shell: bash

    - run: git submodule status -- "${{inputs.prelude-submodule}}" || (rmdir -- "${{inputs.prelude-submodule}}" && git submodule add -- https://github.com/facebook/buck2-prelude "${{inputs.prelude-submodule}}")
      if: inputs.prelude-submodule != ''
      shell: bash

    - run: git submodule update --init --remote -- "${{inputs.prelude-submodule}}"
      if: inputs.prelude-submodule != ''
      shell: bash

    - run: git checkout "${{steps.prelude-hash.outputs.prelude-hash}}"
      working-directory: ${{inputs.prelude-submodule}}
      if: inputs.prelude-submodule != ''
      shell: bash

    - run: sudo apt-get install lld
      if: runner.os == 'Linux'
      shell: bash

    - run: buck2 --version
      shell: bash

    - run: echo prelude-hash=${{steps.prelude-hash.outputs.prelude-hash}}
      shell: bash
