name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

jobs:
  install:
    name: ${{matrix.os == 'ubuntu' && 'Linux' || matrix.os == 'macos' && 'macOS' || matrix.os == 'windows' && 'Windows' || '???'}}
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - run: |
          if buck2 --version; then which buck2; exit 1; fi
          if buck --version; then which buck; exit 1; fi
        shell: bash
        name: test that buck2 is not preinstalled
      - id: install-buck2
        uses: ./
        with:
          prelude-submodule: tools/buck/prelude
      - run: buck --version
      - run: ls tools/buck/prelude
